# Generated by Django 4.1.13 on 2024-03-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyfarm', '0002_alter_login_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
    ]
