# Generated by Django 4.1.13 on 2024-03-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyfarm', '0003_alter_login_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
